mkdir perspective/1_predict_triplet/sampled_triplet_results
mkdir perspective/2_finetune/converted_triplet_results
mkdir perspective/1_predict_triplet/predicted_triplet_results
mkdir perspective/2_finetune/checkpoints

mkdir granularity/sampled_pair_results
mkdir granularity/converted_pair_results
mkdir granularity/predicted_pair_results
mkdir perspective/2_finetune/checkpoints
